== Basics - simple SQL queries:

. Retrieve everything: `select *`
. Retrieve specific: `select f.name, f.membercost from cd.facilities as f;`
. Control rows: `select * from cd.facilities where membercost > 0;`
. Control rows 2: `select facid, name, membercost,monthlymaintenance from cd.facilities where membercost > 0 and membercost < monthlymaintenance/50;`
. Basic string searches: `select * from cd.facilities where name like '%Tenmnis%'`
. Match against multiple possible values: `select * from cd.facilities where facid in (1,5);`
. Classify results into buckets: `select name, case monthlymaintenance > 100 when true then 'expensive' else 'cheap' end as cost from cd.facilities;`
. Working with dates: `select memid, surname, firstname, joindate from cd.members where joindate >= '2012-09-01';`
. Removing dupes and ordering: `select distinct surname from cd.members order by surname asc limit 10 offset 4;` // zwraca 4. stronę wyników
. Combine multi queries: `select surname from cd.members union select name from cd.facilities;`
. Simple aggregate: `select max(joindate) as latest from cd.members;`
. More aggregates: `select firstname, surname, joindate from cd.members where joindate = (select max(joindate) from cd.members);`

