= PGExercises

From: pgexercises.com, a great site which I am VERY grateful to Alistair for.

== Basics - simple SQL queries:

. Retrieve everything: `select *`
. Retrieve specific: `select f.name, f.membercost from cd.facilities as f;`
. Control rows: `select * from cd.facilities where membercost > 0;`
. Control rows 2: `select facid, name, membercost,monthlymaintenance from cd.facilities where membercost > 0 and membercost < monthlymaintenance/50;`
. Basic string searches: `select * from cd.facilities where name like '%Tenmnis%'`
. Match against multiple possible values: `select * from cd.facilities where facid in (1,5);`
. Classify results into buckets: `select name, case monthlymaintenance > 100 when true then 'expensive' else cheap end as cost from cd.facilities;`
. Working with dates: `select memid, surname, firstname, joindate from cd.members where joindate >= '2012-09-01';`
. Removing dupes and ordering: `select distinct surname from cd.members order by surname asc limit 10 offset 4;` // zwraca 4. stronę wyników
. Combine multi queries: `select surname from cd.members union select name from cd.facilities;`
. Simple aggregate: `select max(joindate) as latest from cd.members;`
. More aggregates: `select firstname, surname, joindate from cd.members where joindate = (select max(joindate) from cd.members);`

== Joins and subqueries

.Problem: Members' bookings start times
[source, sql]
----
select b.starttime from cd.bookings b, cd.members m 
where b.memid = m.memid 
and (m.firstname || m.surname) like 'DavidFarrell';

// or

select bks.starttime from cd.bookings bks
	inner join cd.members mems
		on mems.memid = bks.memid
where
	mems.firstname='David'
	and mems.surname='Farrell';
----


.Problem: Work out start times for tennis courts' bookings - https://pgexercises.com/questions/joins/simplejoin2.html
[source, sql]
----
select b.starttime as start, f.name from cd.bookings as b, cd.facilities as f
where b.facid = f.facid
and b.starttime >= '2012-09-21'
and b.starttime < '2012-09-22'
and f.name like 'Tennis%'
order by 1;

// or inner join cd.facilities f on ...
----

.Problem: All members who recommended another
[source, sql]
----

----

.Problem: All members with their recommender
[source, sql]
----

----

.Problem: All members who used a tennis court
[source, sql]
----

----

.Problem: List of costly bookings
[source, sql]
----

----

.Problem: Members and their recommender (no joins)
[source, sql]
----

----

.Problem: List of costly bookings (subquery)
[source, sql]
----

----

